services:
  - type: web
    name: webbanhang-backend
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_NAME
        value: TechShop
      - key: BASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: webbanhang
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_CHARSET
        value: utf8mb4
