<?php
declare(strict_types=1);
class Cart{
    private int $id_gio_hang=0; public function __construct(private PDO $pdo){}
    public function getOrCreateCartByUserId(int $uid):bool{if($uid<=0)return false;$s=$this->pdo->prepare("SELECT id_gio_hang FROM gio_hang WHERE id_nguoi_dung=:u LIMIT 1");$s->execute([':u'=>$uid]);$r=$s->fetch();if($r){$this->id_gio_hang=(int)$r['id_gio_hang'];return true;}$s=$this->pdo->prepare("INSERT INTO gio_hang(id_nguoi_dung) VALUES(:u)");$s->execute([':u'=>$uid]);$this->id_gio_hang=(int)$this->pdo->lastInsertId();return true;}
    public function addItem(int $pid,int $qty=1):bool{if($this->id_gio_hang<=0||$pid<=0||$qty<=0)return false;$s=$this->pdo->prepare("SELECT gia,so_luong_ton,trang_thai FROM san_pham WHERE id_san_pham=:id LIMIT 1");$s->execute([':id'=>$pid]);$p=$s->fetch();if(!$p||$p['trang_thai']!='dang_ban'||(int)$p['so_luong_ton']<=0)return false;$qty=min($qty,(int)$p['so_luong_ton']);$c=$this->pdo->prepare("SELECT so_luong FROM chi_tiet_gio_hang WHERE id_gio_hang=:g AND id_san_pham=:p");$c->execute([':g'=>$this->id_gio_hang,':p'=>$pid]);$e=$c->fetch();if($e)return $this->updateItem($pid,(int)$e['so_luong']+$qty);$i=$this->pdo->prepare("INSERT INTO chi_tiet_gio_hang(id_gio_hang,id_san_pham,so_luong,don_gia) VALUES(:g,:p,:q,:d)");return $i->execute([':g'=>$this->id_gio_hang,':p'=>$pid,':q'=>$qty,':d'=>$p['gia']]);}
    public function updateItem(int $pid,int $qty):bool{if($qty<=0)return $this->removeItem($pid);$s=$this->pdo->prepare("UPDATE chi_tiet_gio_hang SET so_luong=:q WHERE id_gio_hang=:g AND id_san_pham=:p");return $s->execute([':q'=>$qty,':g'=>$this->id_gio_hang,':p'=>$pid]);}
    public function removeItem(int $pid):bool{$s=$this->pdo->prepare("DELETE FROM chi_tiet_gio_hang WHERE id_gio_hang=:g AND id_san_pham=:p");$s->execute([':g'=>$this->id_gio_hang,':p'=>$pid]);return $s->rowCount()>0;}
    public function clearCart():bool{$s=$this->pdo->prepare("DELETE FROM chi_tiet_gio_hang WHERE id_gio_hang=:g");return $s->execute([':g'=>$this->id_gio_hang]);}
    public function getCartItems():array{$s=$this->pdo->prepare("SELECT ctgh.*,ctgh.so_luong*ctgh.don_gia thanh_tien,sp.ten_san_pham,sp.ma_san_pham,sp.hinh_anh_chinh,sp.hinh_anh_chinh AS hinh_anh,sp.so_luong_ton FROM chi_tiet_gio_hang ctgh JOIN san_pham sp ON sp.id_san_pham=ctgh.id_san_pham WHERE ctgh.id_gio_hang=:g ORDER BY ctgh.id_san_pham DESC");$s->execute([':g'=>$this->id_gio_hang]);return $s->fetchAll();}
    public function getTotalPrice():float{$s=$this->pdo->prepare("SELECT COALESCE(SUM(so_luong*don_gia),0) FROM chi_tiet_gio_hang WHERE id_gio_hang=:g");$s->execute([':g'=>$this->id_gio_hang]);return (float)$s->fetchColumn();}
    public function getItemCount():int{$s=$this->pdo->prepare("SELECT COALESCE(SUM(so_luong),0) FROM chi_tiet_gio_hang WHERE id_gio_hang=:g");$s->execute([':g'=>$this->id_gio_hang]);return (int)$s->fetchColumn();}
}
